<?php

namespace AppBundle\Repository;

/**
 * abuseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abuseRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAbuseswithMember(){

        $qb = $this->createQueryBuilder('a');

        $qb->leftJoin('a.comment', 'c');
        $qb->leftJoin('a.member', 'm');

        return $qb->getQuery()
            ->getResult();
    }
}
