<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findCommentsWithAbuses()
    {

        $qb = $this->createQueryBuilder('c');

        $qb->join('c.abuses', 'a');
        $qb->expr()->isNotNull('a');
        $qb->join('c.member', 'm');

        return $qb->getQuery()
            ->getResult();
    }


}
