<?php

namespace AppBundle\Repository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function findImagesByProvider($id){

        $qb = $this->createQueryBuilder('i');
          $qb->leftJoin('i.provider', 'p')
              ->andWhere('p.id like :id')
          ->setParameter('id', $id);

        return $qb->getQuery()
            ->getResult();

    }
}
