<?php

namespace AppBundle\Repository;

/**
 * MailtoUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailtoUserRepository extends \Doctrine\ORM\EntityRepository
{
}
