<?php

namespace AppBundle\Repository;

/**
 * pdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pdfRepository extends \Doctrine\ORM\EntityRepository
{
}
