<?php

namespace AppBundle\Repository;

/**
 * ServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServicesRepository extends \Doctrine\ORM\EntityRepository
{

    public function findServicesWithImage()
    {

        $qb = $this->createQueryBuilder('s');

        $qb->leftJoin('s.image', 'i')->addSelect('i');

        return $qb->getQuery()
            ->getResult();

    }

    public function findValidServicesWithImage()
    {

        $qb = $this->createQueryBuilder('s')
            ->where('s.valid = true');

        $qb->leftJoin('s.image', 'i')->addSelect('i');

        return $qb->getQuery()
            ->getResult();

    }

    public function findValidServices()
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.valid = true');


        return $qb->getQuery()
            ->getResult();
    }

    public function findValidHighlightedServices()
    {
        $qb = $this->createQueryBuilder('s')
            ->where('s.valid = true')
            ->where('s.highlight = true');

        return $qb->getQuery()
            ->getResult();
    }


}
