AppBundle\Entity\Service:
  service-1:
       name: acupuncture
       description: test
       inFront: false
       valid: true
       image: '@img-*'

  service-2:
       name: relaxation
       description: test
       inFront: false
       valid: true
       image: '@img-*'

  service-3:
       name: bronzage
       description: test
       inFront: false
       valid: true
       image: '@img-*'

  service-4:
       name: gastronomie
       description: test
       inFront: false
       valid: true
       image: '@img-*'

  service-5:
       name: coiffure
       description: test
       inFront: false
       valid: true
       image: '@img-*'

  service-6:
       name: relooking
       description: test
       inFront: false
       valid: true
       image: '@img-*'
